# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c6c442e9b0f9dd4e092b32e4066aa1f909a917e05118fee775f286b03bd0fc53cf5bf37fb69c79694520aa5edad93750f65ec1fa7dad66f01e31cb12e0a9a7c

test:
  secret_key_base: aa348bba41fd6119d844b3beac7f537762cf84f309f253d87d7a245e84ca839db7271f37a23d6e3c39e97694e56830108d84ed3d02edc57502571d9ab6c57e95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
